#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd kEpsilon; wclean libso .; wmake libso .; cd ..
cd kOmegaSST; wclean libso .; wmake libso .; cd ..
cd kOmegaSST_F1blend; wclean libso .; wmake libso .; cd ..