#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanCase0

rm -f *.foam
rm -f *.jpg
rm -r logs

#------------------------------------------------------------------------------
