#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Restore 0 Directory
runApplication restore0Dir

# # Initialise fields
# runApplication setExprFields
# runApplication setExprBoundaryFields

# Decomponse mesh
runApplication decomposePar

# Run solver
runParallel $(getApplication)

# Reconstruct mesh
runApplication reconstructPar

# Cleanup
rm -rf processor* > /dev/null 2>&1
rm -rf dynamicCode  > /dev/null 2>&1

# Run Post
python3 post.py  # > /dev/null 2>&1
# python3 post1.py  # > /dev/null 2>&1