#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Start residual monitor
{ while [ -z "$(pidof $(getApplication) | head -n 1 | awk '{print $1}')" ]; do
	sleep 5
done

until [ -z "$(pidof $(getApplication) | head -n 1 | awk '{print $1}')" ]; do
	pkill -f gnuplot > /dev/null 2>&1
	foamMonitor -l -r 1 -i 30 -t Residuals postProcessing/residuals/0/residuals.dat > /dev/null 2>&1 	
done } &

# Run solver
runApplication $(getApplication)

# Cleanup
rm -rf processor* > /dev/null 2>&1
rm -rf dynamicCode  > /dev/null 2>&1

