#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Decomponse mesh
runApplication decomposePar -copyZero

# Run solver
runParallel $(getApplication)

# Reconstruct mesh
runApplication reconstructPar

# Postprocessing
python3 tools/postProcess/probes_to_csv_U.py
python3 tools/postProcess/probes_to_csv_k.py

# Cleanup
rm -rf processor* > /dev/null 2>&1
rm -rf dynamicCode  > /dev/null 2>&1

# Run Post
python3 post.py  # > /dev/null 2>&1