#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# # Compile custom code
# cd tools/openfoam7/kEpsilon; wmake libso . >> ../../../log.wmake;  cd ../../..;
# cd tools/openfoam7/kOmegaSST; wmake libso . >> ../../../log.wmake;  cd ../../..;
# cd tools/openfoam7/kOmegaSST_F1blend; wmake libso . >> ../../../log.wmake;  cd ../../..;

# Run solver
runApplication $(getApplication)

# Calculate yPlus
$(getApplication) -postProcess -func yPlus -noZero -latestTime > /dev/null 2>&1

# Cleanup
rm -rf processor* > /dev/null 2>&1
rm -rf dynamicCode  > /dev/null 2>&1

# Run Post
python3 post.py  # > /dev/null 2>&1

# # Plot residuals
# foamMonitor -l -t Residuals postProcessing/residuals/0/residuals.dat > /dev/null 2>&1 